# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
#- script: /Applications/SnowSQL.app/contents/MacOS/snowsql -a va_demo32.us-east-1 -u rshetler -q "show stages;"
#  displayName: 'TestSnowsql'

- script: snowsql -a va_demo32.us-east-1 -u rshetler -q "show stages;"
  workingDirectory: /Applications/SnowSQL.app/contents/MacOS
  displayName: show stages
  env:
    aVarFromYaml: someValue

#- script: |
#   echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
